export type ApiTemplateKey = "nightLanternRedBlackHanfu";

export type TemplateDynasty = "唐" | "宋" | "元" | "明" | "清" | "新中式";
export type TemplateCategory = TemplateDynasty | "敦煌" | "旗袍";
export type TemplateFilter = "热门" | "最新" | "会员专属" | "免费可用" | "已收藏";

export type HanfuTemplate = {
  id: string;
  apiTemplateKey: ApiTemplateKey;
  name: string;
  dynasty: TemplateDynasty;
  category: TemplateCategory;
  label: string;
  styleTags: string[];
  filters: TemplateFilter[];
  description: string;
  previewUrl: string;
  galleryImages: string[];
  creditCost: number;
  isPremium: boolean;
  recommendedPhotoType: string;
  generationCount: number;
  audience: string;
  usageTips: string;
};

const defaultGallery = [
  "/images/hanfu-hero/palace-red-02.jpg",
  "/images/hanfu-hero/palace-red-03.jpg",
  "/images/hanfu-hero/palace-red-01.jpg",
  "/images/hanfu-hero/festival-lantern-01.jpg",
  "/images/hanfu-hero/spring-pink-01.jpg",
  "/images/hanfu-hero/jade-temple-01.jpg",
];

const makeTemplate = (
  template: Omit<
    HanfuTemplate,
    "apiTemplateKey" | "creditCost" | "generationCount" | "galleryImages" | "recommendedPhotoType" | "audience" | "usageTips"
  > &
    Partial<Pick<HanfuTemplate, "galleryImages" | "recommendedPhotoType" | "audience" | "usageTips">>
): HanfuTemplate => ({
  apiTemplateKey: "nightLanternRedBlackHanfu",
  creditCost: 10,
  generationCount: 4,
  galleryImages: template.galleryImages ?? defaultGallery,
  recommendedPhotoType: template.recommendedPhotoType ?? "清晰正脸照，面部无遮挡，光线充足。",
  audience: template.audience ?? "适合想快速获得高级汉服写真氛围的用户。",
  usageTips: template.usageTips ?? "建议选择背景简洁、五官清晰的照片，生成效果更稳定。",
  ...template,
});

export const hanfuTemplates: HanfuTemplate[] = [
  makeTemplate({
    id: "tangGlamour",
    name: "盛唐金影",
    dynasty: "唐",
    category: "唐",
    label: "唐风",
    styleTags: ["唐风", "热门", "宫廷感"],
    filters: ["热门", "最新"],
    description: "适合喜欢华丽唐风、金色宫廷氛围的汉服写真。",
    previewUrl: "/images/hanfu-hero/palace-red-02.jpg",
    isPremium: false,
    audience: "适合喜欢盛唐华服、金色妆造和高贵氛围的用户。",
  }),
  makeTemplate({
    id: "palaceLantern",
    name: "宫灯夜宴",
    dynasty: "唐",
    category: "唐",
    label: "唐风",
    styleTags: ["唐风", "夜宴", "会员专属"],
    filters: ["会员专属"],
    description: "宫灯映照下的唐风夜宴写真，适合浓郁节庆氛围。",
    previewUrl: "/images/hanfu-hero/festival-lantern-01.jpg",
    isPremium: true,
  }),
  makeTemplate({
    id: "tangLady",
    name: "唐风仕女",
    dynasty: "唐",
    category: "唐",
    label: "唐风",
    styleTags: ["唐风", "仕女", "温婉"],
    filters: ["最新"],
    description: "温婉唐风仕女感，突出发饰、妆容与柔和光影。",
    previewUrl: "/images/hanfu-hero/palace-red-03.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "goldHairpin",
    name: "华服金钗",
    dynasty: "唐",
    category: "唐",
    label: "唐风",
    styleTags: ["华服", "金钗", "唐风"],
    filters: ["热门"],
    description: "华服金钗主题，适合精致头饰与明艳妆造。",
    previewUrl: "/images/hanfu-hero/palace-red-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "songElegance",
    name: "宋韵清婉",
    dynasty: "宋",
    category: "宋",
    label: "宋韵",
    styleTags: ["宋韵", "免费", "清雅"],
    filters: ["免费可用"],
    description: "清雅克制的宋韵写真，适合喜欢淡雅、书卷气风格的用户。",
    previewUrl: "/images/hanfu-hero/palace-red-03.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "teaGathering",
    name: "茶席雅集",
    dynasty: "宋",
    category: "宋",
    label: "宋韵",
    styleTags: ["宋韵", "茶席", "雅集"],
    filters: ["免费可用"],
    description: "茶席雅集氛围，强调清淡色彩与静谧文人感。",
    previewUrl: "/images/hanfu-hero/spring-pink-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "landscapePlain",
    name: "山水素衣",
    dynasty: "宋",
    category: "宋",
    label: "宋韵",
    styleTags: ["山水", "素衣", "宋韵"],
    filters: ["最新"],
    description: "山水素衣主题，适合干净背景与淡妆正脸照。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "courtyardShadow",
    name: "庭院清影",
    dynasty: "宋",
    category: "宋",
    label: "宋韵",
    styleTags: ["宋韵", "庭院", "免费"],
    filters: ["免费可用"],
    description: "庭院清影氛围，适合柔和自然光和温婉表情。",
    previewUrl: "/images/hanfu-hero/palace-red-02.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "grasslandHu",
    name: "草原胡风",
    dynasty: "元",
    category: "元",
    label: "元风",
    styleTags: ["元风", "草原", "胡风"],
    filters: ["最新"],
    description: "更具异域感的元风写真，适合强轮廓与大气构图。",
    previewUrl: "/images/hanfu-hero/palace-red-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "yuanPalace",
    name: "元宫华服",
    dynasty: "元",
    category: "元",
    label: "元风",
    styleTags: ["元风", "宫廷", "华服"],
    filters: ["热门"],
    description: "元宫华服主题，强调厚重服饰层次与宫廷气质。",
    previewUrl: "/images/hanfu-hero/festival-lantern-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "frontierMoon",
    name: "塞外明月",
    dynasty: "元",
    category: "元",
    label: "元风",
    styleTags: ["塞外", "明月", "元风"],
    filters: ["最新"],
    description: "塞外月色氛围，适合冷调、清冷和故事感写真。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "brocadeRider",
    name: "锦袍骑影",
    dynasty: "元",
    category: "元",
    label: "元风",
    styleTags: ["锦袍", "骑影", "元风"],
    filters: ["热门"],
    description: "锦袍骑影主题，适合更英气和动态感的古风写真。",
    previewUrl: "/images/hanfu-hero/palace-red-03.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "mingFormal",
    name: "明制端庄",
    dynasty: "明",
    category: "明",
    label: "明制",
    styleTags: ["明制", "端庄", "典雅"],
    filters: ["最新"],
    description: "明制端庄风，适合正式、典雅、对称构图的写真。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "phoenixCrown",
    name: "凤冠霞帔",
    dynasty: "明",
    category: "明",
    label: "明制",
    styleTags: ["明制", "凤冠", "会员专属"],
    filters: ["会员专属", "热门"],
    description: "凤冠霞帔主题，适合华丽明制礼服和仪式感成片。",
    previewUrl: "/images/hanfu-hero/palace-red-02.jpg",
    isPremium: true,
  }),
  makeTemplate({
    id: "boudoirLady",
    name: "庭院闺秀",
    dynasty: "明",
    category: "明",
    label: "明制",
    styleTags: ["明制", "庭院", "闺秀"],
    filters: ["免费可用"],
    description: "庭院闺秀主题，适合温柔、安静、含蓄的写真表达。",
    previewUrl: "/images/hanfu-hero/spring-pink-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "redWallSnow",
    name: "朱墙雪景",
    dynasty: "明",
    category: "明",
    label: "明制",
    styleTags: ["明制", "雪景", "朱墙"],
    filters: ["热门"],
    description: "朱墙雪景主题，适合冷暖对比强烈的古风写真。",
    previewUrl: "/images/hanfu-hero/palace-red-03.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "qingPalace",
    name: "清宫雅韵",
    dynasty: "清",
    category: "清",
    label: "清韵",
    styleTags: ["清韵", "宫廷", "典雅"],
    filters: ["最新"],
    description: "清宫雅韵主题，适合细腻妆造和宫廷肖像感。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "qipaoFlower",
    name: "旗装花影",
    dynasty: "清",
    category: "旗袍",
    label: "清韵",
    styleTags: ["旗装", "花影", "清韵"],
    filters: ["免费可用"],
    description: "旗装花影风格，适合柔和花影与东方肖像感。",
    previewUrl: "/images/hanfu-hero/spring-pink-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "palacePortrait",
    name: "宫廷肖像",
    dynasty: "清",
    category: "清",
    label: "清韵",
    styleTags: ["清韵", "宫廷", "肖像"],
    filters: ["热门"],
    description: "清宫肖像主题，强调精致妆容与稳定构图。",
    previewUrl: "/images/hanfu-hero/palace-red-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "winterRed",
    name: "冬雪红妆",
    dynasty: "清",
    category: "清",
    label: "清韵",
    styleTags: ["清韵", "冬雪", "热门"],
    filters: ["热门"],
    description: "冬雪红妆主题，适合红衣、雪景和强烈节日氛围。",
    previewUrl: "/images/hanfu-hero/festival-lantern-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "bluePorcelain",
    name: "青花瓷影",
    dynasty: "新中式",
    category: "新中式",
    label: "新中式",
    styleTags: ["新中式", "青花", "热门"],
    filters: ["热门", "最新"],
    description: "青花瓷影主题，适合现代东方审美和清透色彩。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "modernQipao",
    name: "现代旗袍",
    dynasty: "新中式",
    category: "旗袍",
    label: "新中式",
    styleTags: ["旗袍", "新中式", "免费"],
    filters: ["免费可用", "最新"],
    description: "现代旗袍主题，适合更轻盈、时尚的东方写真。",
    previewUrl: "/images/hanfu-hero/spring-pink-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "modernGuofeng",
    name: "国风时尚",
    dynasty: "新中式",
    category: "新中式",
    label: "新中式",
    styleTags: ["国风", "时尚", "新中式"],
    filters: ["热门"],
    description: "国风时尚主题，适合现代杂志感的东方视觉。",
    previewUrl: "/images/hanfu-hero/palace-red-03.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "orientalMagazine",
    name: "东方杂志",
    dynasty: "新中式",
    category: "新中式",
    label: "新中式",
    styleTags: ["东方", "杂志", "新中式"],
    filters: ["最新"],
    description: "东方杂志主题，适合简洁高级的现代汉服写真。",
    previewUrl: "/images/hanfu-hero/palace-red-02.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "qinHanNoir",
    name: "秦汉玄色",
    dynasty: "明",
    category: "元",
    label: "秦汉",
    styleTags: ["秦汉", "玄色", "热门"],
    filters: ["热门"],
    description: "深色古风质感，适合喜欢冷峻、侠气、秦汉氛围的用户。",
    previewUrl: "/images/hanfu-hero/palace-red-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "drunkenFlower",
    name: "醉花影",
    dynasty: "新中式",
    category: "唐",
    label: "国风",
    styleTags: ["国风", "花影", "热门"],
    filters: ["热门"],
    description: "灯火与花影交织的国风写真，氛围更热烈浓郁。",
    previewUrl: "/images/hanfu-hero/festival-lantern-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "pearBlossom",
    name: "梨花幽韵",
    dynasty: "清",
    category: "新中式",
    label: "旗袍",
    styleTags: ["梨花", "新中式", "免费"],
    filters: ["免费可用"],
    description: "淡雅梨花氛围，适合喜欢清新、温柔、低饱和写真风格的用户。",
    previewUrl: "/images/hanfu-hero/spring-pink-01.jpg",
    isPremium: false,
  }),
  makeTemplate({
    id: "dunhuangMuse",
    name: "敦煌飞天",
    dynasty: "唐",
    category: "敦煌",
    label: "敦煌",
    styleTags: ["敦煌", "飞天", "会员专属"],
    filters: ["会员专属", "热门"],
    description: "敦煌飞天灵感写真，适合喜欢壁画感、异域色彩和高级艺术氛围的用户。",
    previewUrl: "/images/hanfu-hero/jade-temple-01.jpg",
    isPremium: true,
  }),
];

export const dynastyTabs: TemplateDynasty[] = ["唐", "宋", "元", "明", "清", "新中式"];

export const featuredTemplateIds = [
  "tangGlamour",
  "songElegance",
  "qinHanNoir",
  "drunkenFlower",
  "pearBlossom",
  "dunhuangMuse",
  "bluePorcelain",
  "winterRed",
  "palaceLantern",
  "modernQipao",
];

export const templateLibraryIds = [
  "tangGlamour",
  "songElegance",
  "qinHanNoir",
  "drunkenFlower",
  "pearBlossom",
  "dunhuangMuse",
  "bluePorcelain",
  "winterRed",
  "palaceLantern",
  "modernQipao",
  "courtyardShadow",
  "phoenixCrown",
];

export const templateLibraryData = templateLibraryIds
  .map((templateId) => hanfuTemplates.find((template) => template.id === templateId))
  .filter((template): template is HanfuTemplate => Boolean(template));

export function getTemplateById(id: string) {
  return hanfuTemplates.find((template) => template.id === id) ?? null;
}
