// .source/server is generated by fumadocs-mdx during install/build/dev.
// Treat it as derived output, not hand-written source.
import { docs } from '@/.source/server';
import { loader } from 'fumadocs-core/source';
import { docsI18n } from '@/lib/docs-i18n';

export const source = loader({
  baseUrl: '/docs',
  i18n: docsI18n,
  source: docs.toFumadocsSource(),
});
