// AUTO-GENERATED by scripts/generate-template-registry.mjs
// DO NOT EDIT MANUALLY.
// Generated at: 2026-07-13T02:25:31.796Z

import template_schema_test from "./items/schema-test/template.json";

const TEMPLATE_REGISTRY: unknown[] = [
  template_schema_test as unknown,
];

export { TEMPLATE_REGISTRY };
